---
- name: install docker
  yum:
    name: docker
    state: latest

- name: install epel-release
  yum:
    name: epel-release

- name: epel install docker-compose
  yum:
    name: docker-compose
    state: latest
    enablerepo: epel